export const systemPlans = [
  {
    id: 'plan-bronze',
    code: 'bronze',
    name: 'Bronze',
    monthlyPrice: 49.90,
    semesterDiscount: 5,
    annualDiscount: 15,
    sellerLimit: 2,
    productLimit: null,
    catalogLimit: 1,
    photoLimit: 5,
    franchiseeLimit: 0,
    socialWeight: 1,
    trafficPriority: 'baixa',
    features: {
      catalog: true,
      products: true,
      cart: true,
      minimumOrder: true,
      productVideo: true,
      customerLogin: true,
      whatsappOrder: true,
      temporaryStoreDisable: true,
      wholesaleRetail: true,
      productGrid: true,
      meetingPoints: true,
      stock: false,
      customDomain: false,
      reviews: false,
      commercialIntelligence: false,
      storePersonalization: false,
      franchisees: false,
      sellerCommission: false,
      vaxLar: false,
    },
  },
  {
    id: 'plan-prata',
    code: 'prata',
    name: 'Prata',
    monthlyPrice: 94.90,
    semesterDiscount: 5,
    annualDiscount: 15,
    sellerLimit: 4,
    productLimit: null,
    catalogLimit: 3,
    photoLimit: 10,
    franchiseeLimit: 2,
    socialWeight: 2,
    trafficPriority: 'media',
    features: {
      catalog: true,
      products: true,
      cart: true,
      minimumOrder: true,
      productVideo: true,
      customerLogin: true,
      whatsappOrder: true,
      temporaryStoreDisable: true,
      wholesaleRetail: true,
      productGrid: true,
      meetingPoints: true,
      stock: true,
      customDomain: true,
      reviews: true,
      commercialIntelligence: true,
      storePersonalization: true,
      franchisees: true,
      sellerCommission: false,
      vaxLar: false,
    },
  },
  {
    id: 'plan-ouro',
    code: 'ouro',
    name: 'Ouro',
    monthlyPrice: 144.90,
    semesterDiscount: 5,
    annualDiscount: 15,
    sellerLimit: null,
    productLimit: null,
    catalogLimit: null,
    photoLimit: 10,
    franchiseeLimit: null,
    socialWeight: 3,
    trafficPriority: 'alta',
    features: {
      catalog: true,
      products: true,
      cart: true,
      minimumOrder: true,
      productVideo: true,
      customerLogin: true,
      whatsappOrder: true,
      temporaryStoreDisable: true,
      wholesaleRetail: true,
      productGrid: true,
      meetingPoints: true,
      stock: true,
      customDomain: true,
      reviews: true,
      commercialIntelligence: true,
      storePersonalization: true,
      franchisees: true,
      sellerCommission: true,
      vaxLar: false,
    },
  },
]

export const publicPlanCodes = systemPlans.map((plan) => plan.code)
