import type { Product, Store } from './types'

export const store: Store = {
  slug: 'casa-norte',
  name: 'Casa Norte',
  eyebrow: 'Atacado de moda e acessórios',
  tagline: 'Peças que giram. Pedido sem enrolação.',
  minimumOrder: 400,
  sellers: [
    { slug: 'marina', name: 'Marina', phone: '5571999999999' },
    { slug: 'bianca', name: 'Bianca', phone: '5571888888888' },
  ],
}

export const products: Product[] = [
  {
    id: 'p1',
    sku: 'CN-0182',
    name: 'Bolsa Estruturada Siena',
    description: 'Bolsa média com alça regulável e ferragens foscas.',
    price: 48.9,
    category: 'Bolsas',
    pack: 'Kit com 3 cores',
    colors: ['Preto', 'Caramelo', 'Off white'],
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=88',
    featured: true,
  },
  {
    id: 'p2',
    sku: 'CN-0311',
    name: 'Camisa Ampla Linho',
    description: 'Modelagem ampla, toque leve e acabamento limpo.',
    price: 42,
    category: 'Roupas',
    pack: 'Grade P/M/G',
    colors: ['Areia', 'Branco', 'Preto'],
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1200&q=88',
  },
  {
    id: 'p3',
    sku: 'CN-0290',
    name: 'Óculos Bossa',
    description: 'Armação leve com lente escura e proteção UV400.',
    price: 21.5,
    category: 'Acessórios',
    pack: 'Mínimo 6 un.',
    colors: ['Tartaruga', 'Preto'],
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=88',
  },
  {
    id: 'p4',
    sku: 'CN-0412',
    name: 'Vestido Midi Flora',
    description: 'Midi fluido, alça larga e recorte reto nas costas.',
    price: 59.9,
    category: 'Roupas',
    pack: 'Grade P/M/G',
    colors: ['Terracota', 'Azul'],
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1200&q=88',
    featured: true,
  },
  {
    id: 'p5',
    sku: 'CN-0504',
    name: 'Carteira Compacta Leme',
    description: 'Formato compacto com fechamento por botão e seis divisórias.',
    price: 16.9,
    category: 'Carteiras',
    pack: 'Kit com 5 un.',
    colors: ['Preto', 'Vinho', 'Caramelo'],
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=1200&q=88',
  },
  {
    id: 'p6',
    sku: 'CN-0607',
    name: 'Tênis Casual Rua',
    description: 'Solado baixo, construção leve e palmilha macia.',
    price: 54,
    category: 'Calçados',
    pack: 'Grade 34 ao 39',
    colors: ['Branco', 'Preto'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=88',
  },
  {
    id: 'p7',
    sku: 'CN-0662',
    name: 'Bolsa Baguete Centro',
    description: 'Perfil baixo, alça curta e acabamento acetinado.',
    price: 39.9,
    category: 'Bolsas',
    pack: 'Kit com 3 un.',
    colors: ['Preto', 'Café', 'Creme'],
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=88',
  },
  {
    id: 'p8',
    sku: 'CN-0728',
    name: 'Brinco Argola Serena',
    description: 'Argola média, banho dourado e fechamento click.',
    price: 12,
    category: 'Acessórios',
    pack: 'Cartela com 6 pares',
    colors: ['Dourado'],
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=88',
  }
]
